### ISSUE TITLE
Code is not available

### ISSUE THREAD

**Issue by SimonGoring** [jtipton25/compositional-inverse-prediction#1]
Hi John, we're at a pollen-based climate modeling workshop and people were interested in the method & comparisons.  Could you post the code for the paper?  In the paper it says the code is available here.

**Comment by jtipton25** [comment]
Hey Simon. I'm driving a moving truck across the country this week and
won't have time to get the code up. The short answer is that I used the
rioja package for the wa (weighted averaging) and mlrc (maximun likelihood
response curve) models and the analogue package for mat (modern analogue).

I also used random forest and that predicted very well but without the
ecological inference in our model.

I'm putting all of the code into a package and should have that up soon.
I'll let you know when it's ready
